#define INITIAL_WINDOW_WIDTH 1280
#define INITIAL_WINDOW_HEIGHT 720

enum DebugView
{
    DEBUG_VIEW_NONE       = 0,
    DEBUG_VIEW_POSITION   = 1,
    DEBUG_VIEW_NORMAL     = 2,
    DEBUG_VIEW_BASE_COLOR = 3,
    DEBUG_VIEW_METALLIC   = 4,
    DEBUG_VIEW_ROUGHNESS  = 5
};